### ISSUE TITLE
As a user I want to be able to choose the forecast window

### ISSUE THREAD

**Issue by tjohnson-scottlogic** [ECMWFCode4Earth/vAirify#209]
Ability to choose the forecast window, the default being 1, up to 5 days

  Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
- [x] Test Cases Executed
- [x] Test Charters Executed
- [x] Regression tests executed
- [x] Automation Tests added to project

**Comment by mnyamunda-scottlogic** [comment]
- Forecast window tab exists in the banner on both pages
- Window can be selected and contain a dropdown of 1-5
- Window default to value "1" by default
- Window only triggers change when OK is pressed.
- Since keyboard entry is allowed, error should fire on any value 1 <  and > 5 

exploratory

**Comment by mwalker-scottlogic** [comment]
Finding

### Description

- 'Verify on changing the forecast base time, the measurement summary API is called proportionately' test failing in `summary_page_api_calls.spec.ts`
- expecting a change of base date to 2024-07-03T12:00:00 to generate 41 requests to the measurement summary API, but actually gets a lot more
- Reproducing this manually, it seems to make requests right up to present time'
- To exacerbate this, changing the base date far back to generate a lot of requests crashes the app

### Steps to reproduce:

- On production, navigate to summary page
- Set forecast window to 5
- change forecast base date to 1st Jan 1901 12:00
- inspect network
- scroll mouse around

Expected:
- 41 calls to measurement summary API

Actual:

- App crashes


![Image](https://github.com/user-attachments/assets/56863342-64f4-4786-9ebe-1f2773f369f2)

**Comment by mnyamunda-scottlogic** [comment]
### To-do

Since measurements summary doesn't have fields for a `date_from` and `date_to` we instead to write tests like this:


![Image](https://github.com/user-attachments/assets/57b66096-be3d-402a-b209-a41120b56907)

- By default, forecast window 1 sends 9 requests and 5 sends 41 (Previously written tests pass with this logic, should be confirmed with devs) 
- So, we just need to cover window options 2-5.

### Findings
- On Prod we seem to only be getting a /forecast endpoint request being sent with no /summary


![Image](https://github.com/user-attachments/assets/5addc0f3-60f9-415f-a064-a3bcf21f0a5e)

- Locally we get 1 /forecast and 9 - 41 /summary requests sent when the window is changed. (Should be investigated as it may be a local issue with me)

**Comment by mnyamunda-scottlogic** [comment]
[Exploratory](https://github.com/ECMWFCode4Earth/vAirify/wiki/Charter-30:-Explore-forecast-window-with-seeded-database-data-to-ensure-correct-functionality), seed database and verify that the forecast window filters DB data accurately

**Comment by mnyamunda-scottlogic** [comment]
When a forecast window is selected we expect to filter out everything besides the measurements in range.

Recreation:

Expected Behaviour: 
If base_time is 01/07/2024 and we have forecast window of 1 then we expect the request made to contain:
`valid_time_from` to equal '2024-07-01T00%3A00%3A00.000Z'
`valid_time_to` to equal '2024-07-02T00%3A00%3A00.000Z'

Actual Behaviour:
`valid_time_from` is '2024-07-01T00%3A00%3A00.000Z'
`valid_time_to` is  '2024-08-29T13%3A54%3A38.509Z'  (or whatever the system time is)

This means that essentially the entire 5 day range is shown on the table and filtering doesn't happen API wise

**Comment by mnyamunda-scottlogic** [comment]
Fixed and tested with API call assertions and [charter](https://github.com/ECMWFCode4Earth/vAirify/wiki/Charter-30:-Explore-forecast-window-with-seeded-database-data-to-ensure-correct-functionality)
