### ISSUE TITLE
create data textures for CAMS gridded forecast

### ISSUE THREAD

**Issue by sebsteinig** [ECMWFCode4Earth/vAirify#73]
## Rationale
- we want to show (or at least test the feasibility of showing) global/regional maps of the forecast data to add spatial context to the city comparison
- e.g. if the forecast "misses" some pollution event in some cities, the dashboard can give us an idea about what went wrong (e.g. winds blew the pollutants too far north) 
- to handle/visualise the data easily in the frontend, we need to convert the GRIB data into a data texture (bitmap)
- conversion is done in Python, necessary steps:
    - reading global GRIB files
    - normalise the data to [0,255] range
    - write the data to bitmap (WebP format for efficient, lossless compression)
    - one variable per texture for incremental loading by the frontend (winds U and V components can be saved as red and green channels in RGB)
    - all time steps are stitched together horizontally as a movie strip to allow efficient time interpolation on the frontend GPU

## Acceptance Criteria
- process to create data textures added to ETL pipeline
- one data texture each for variables: overall AQI, PM2.5, PM10, O3, NO2, SO2, winds
- textures are added to MongoDB in a new collection "textures" with key <forecast_base_time> and <variable>
- conversion metadata (units, dynamical min and max values to convert back from [0,255] range) added to collection
- GRIB to bitmap conversion is tested with mock data

### example data texture

![tfgzk_winds mm](https://github.com/ECMWFCode4Earth/vAirify/assets/80361118/d73f6645-c152-4470-9a5b-9654f116bb2f)

  Test Checklist:
- [ ] Test Analysis & discussion with developer
- [ ] Write Test Cases / Charters
- [ ] Test Cases & Charters Reviewed
- [ ] Test Cases Executed
- [ ] Test Charters Executed
- [x] Regression tests executed
- [ ] Automation Tests added to project

**Comment by mwalker-scottlogic** [comment]
Backend tests - PASSED ✅ 

![Image](https://github.com/user-attachments/assets/21689893-0936-41f8-b804-99b370de3aa4)

Frontend tests - 33 Failed, all to do with snapshots

![Image](https://github.com/user-attachments/assets/ab2e590e-e7f3-4a8c-9798-7fee2efa7796)

AQI graph snapshot is failing because the line has changed

![Image](https://github.com/user-attachments/assets/0ee991c3-efa3-4782-bdd9-b008712d9234)

Pollutant graphs are failing as expecting dimensions 600 x 400 but getting 601 x 400

![Image](https://github.com/user-attachments/assets/ba27ad74-48e9-4efb-9b13-678d910aaba6)

No2 is correct dimensions but 192 pixels (ratio 0.01 of all image pixels) are different.
 
![Image](https://github.com/user-attachments/assets/6d2b2004-8b60-4268-baa4-f249639624b3)


note: webkit tests are expecting and getting a different size: Expected an image 1200px by 800px, received 1202px by 800px

**Comment by mwalker-scottlogic** [comment]
Regression Tests Passed ✅ 

- Backend system tests

![Image](https://github.com/user-attachments/assets/3989ec5a-3dee-46cd-9c35-b5f5e2d8a842)

Frontend system tests

![Image](https://github.com/user-attachments/assets/2d2b3065-6430-4c8b-b495-3dd67166e5e2)

# #

[Playwright Regression 25.07.24.pdf](https://github.com/user-attachments/files/16379307/Playwright.Regression.25.07.24.pdf)

**Comment by mwalker-scottlogic** [comment]
### Test Analysis

**Comment by mnyamunda-scottlogic** [comment]
### Findings 


![Image](https://github.com/user-attachments/assets/3d4b786d-0edf-4c8d-9cdd-4fc7ee1af74e)

Possible duplicate entries due to change of key parameter types.

**Comment by mnyamunda-scottlogic** [comment]
Image comparison added. Still possible work to be done around grib point to bitmap conversion. This could be useful to simply prove that the image set we compare against has been transformed correctly.

**Comment by mnyamunda-scottlogic** [comment]
Used pygrib to navigate through messages 

![Image](https://github.com/user-attachments/assets/23ade6e4-33fa-414a-a0dc-d0f17c04e6ef)

Branch to take a value from GRIB to Bitmap  `mnyamunda/data-texture-calculation`  

### Actions

- Need to confirm with Seb if the data is being transformed/normalised in the way I have done it. If so, then we can isolate a GRIB value and do pen and paper calculation to end up with the same Bitmap value 0-255 



![Image](https://github.com/user-attachments/assets/fcaccd23-7e5b-426a-8efa-4f94f2ff385c)

- Maybe if there is a way to stub the data textures before they are turned into .webp and be able to load them and see their pixel values.

**Comment by mnyamunda-scottlogic** [comment]
![Image](https://github.com/user-attachments/assets/937ab135-840b-46f2-8901-155c6be8893a)

# todo 
- Now we have a script that shows bitmap values from whichever coords we enter:
![Image](https://github.com/user-attachments/assets/f6a25915-9d36-4333-8dab-bf26b962a6a4)

- Need to pull an already generated webp and also do the same. However we may need to stub our data textures code to the point before it is turned from bmp to webp. Then we load that in using PIL library to check the same coords on each Image.
- Note: Our height stays the same y = 451, only our x is different since the data_textures generated by the ETL are in a movie strip (14400 x 451)  Hence, when picking coords ensure that x is not set too high.
- Currently the setup is using a single level grib within the same folder. 
![Image](https://github.com/user-attachments/assets/5ce6f132-399c-4a46-98bc-75fced18a37c)

- Essentially you will run the etl, then drag the single level grib file that was generated into system_tests -> data_textures. 
   Then we will just have to tweak the name of our single_grib variable to suit the recently generated grib. 

This can most likely be automated. It will be an assertion that looks at the same coordinate bitmap values and asserts that they are the same.
